In [1]:
import numpy as np
import pandas as pd

In [4]:
train_df = pd.read_csv("Data/train.csv")
test_df = pd.read_csv("Data/test.csv")

In [5]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
train_df[train_df['target'] == 0].head()

id keyword location                          text  target
15  23     NaN      NaN                What's up man?       0
16  24     NaN      NaN                 I love fruits       0
17  25     NaN      NaN              Summer is lovely       0
18  26     NaN      NaN             My car is so fast       0
19  28     NaN      NaN  What a goooooooaaaaaal!!!!!!       0

In [7]:
train_df[train_df['target'] == 1].head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
vectorizer = CountVectorizer()
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(train_df['text'].values[:11])
print(vectorizer.get_feature_names())
print(len(vectorizer.get_feature_names()))

['000', '13', '20', 'across', 'afraid', 'alaska', 'all', 'allah', 'an', 'and', 'are', 'area', 'areas', 'as', 'asked', 'being', 'both', 'building', 'by', 'cafire', 'california', 'can', 'canada', 'causes', 'closed', 'colorado', 'coming', 'county', 'deeds', 'died', 'directions', 'disaster', 'due', 'earthquake', 'emergency', 'evacuation', 'expected', 'far', 'fire', 'flash', 'flood', 'flooding', 'forest', 'forgive', 'from', 'got', 'happening', 'heat', 'heavy', 'hill', 'hwy', 'in', 'into', 'is', 'just', 'la', 'lake', 'manitou', 'may', 'near', 'no', 'notified', 'now', 'of', 'officers', 'on', 'or', 'orders', 'other', 'our', 'people', 'photo', 'place', 'pours', 'rain', 'reason', 'receive', 'residents', 'rockyfire', 'ronge', 'ruby', 'sask', 'school', 'see', 'sent', 'shelter', 'smoke', 'so', 'springs', 'street', 'streets', 'that', 'the', 'there', 'this', 'three', 'to', 'top', 'tornado', 'update', 'us', 'wave', 'wildfires', 'woods']
104


In [10]:
vectorizer.get_stop_words

<bound method VectorizerMixin.get_stop_words of CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>

In [11]:
X = vectorizer.fit_transform(train_df['text'].values)
X_test =vectorizer.transform(test_df['text'].values)

In [12]:
from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, train_df['target'], test_size=0.33, random_state=42)
clf = LogisticRegression().fit(X_train, y_train)


In [13]:
clf.score(X_train, y_train)

0.9752941176470589

In [14]:
clf.score(X_test, y_test)

0.8034222045364107

In [15]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores

array([0.77473066, 0.8127451 , 0.76862745, 0.76176471, 0.8047105 ])

In [16]:
# Lasso does not perform well
lasso = Lasso(0.001).fit(X_train, y_train)

print(cross_val_score(lasso, X_train, y_train, cv=3))

[0.29951412 0.30433349 0.29073939]


In [17]:
import pickle

Pkl_Filename = "Data/simple_LR_model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)

In [18]:
# Read model from pickle
with open('Data/simple_LR_model.pkl', 'rb') as file:  
    clf = pickle.load(file)

clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
from config import conn

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [43]:
keyword = 'earthquake'
cur = conn.cursor()
cur.execute(
    "SELECT text, keyword, url FROM disaster_tweets WHERE keyword='{}'".format(keyword))
data = cur.fetchall()

In [44]:
data

[('#Earthquake M3.7 New Zealand 3mins ago 13 Feb 19:16 UTC - report/info: \nhttps://t.co/WTz0pRScET',
  'earthquake',
  'https://twitter.com/EQAlerts/status/1228035909116997633'),
 ('U all still Ned to CUPTURE HUNG BURN THE FUCKERSS alive to survive to leave on my planet Earth I well show no mercy to Yous all .. U all be sweming inside VOLCANO  wipe the fuck out .with MAGNITUDE EARTHQUAKE 20/20',
  'earthquake',
  'https://twitter.com/RiseSphinx/status/1228035876904521728'),
 ('A M3.7 earthquake has been reported by the GeoNetNZ for 5 km east of Seddon. Link: https://t.co/Ia45KmO14U',
  'earthquake',
  'https://twitter.com/quakeupdates/status/1228035846407737350'),
 ('M3.7 quake causing moderate shaking near Seddon https://t.co/dPKIBoG5MG',
  'earthquake',
  'https://twitter.com/geonet/status/1228035714375278592'),
 ("Are you prepared for the Cascadia earthquake? This is important info for all of us in Oregon. At UO, we're studying how diverse populations in Oregon perceive and respond

In [45]:
for tweet in data[:1]:
        X_test =vectorizer.transform(test_df['text'].values)
        

In [46]:
tweets = [tweet[0] for tweet in data]

In [47]:
X_test = vectorizer.transform(tweets)

In [48]:
clf.predict(X_test)

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 1])

In [42]:
tweets[0]

'"WEATHER is a must-read addition to the growing ranks of climate fiction, a genre that accepts climate catastrophe as the unavoidable context within which all modern stories unfold." https://t.co/1GyRoSEw7W'

In [49]:
tweets[1]

'U all still Ned to CUPTURE HUNG BURN THE FUCKERSS alive to survive to leave on my planet Earth I well show no mercy to Yous all .. U all be sweming inside VOLCANO  wipe the fuck out .with MAGNITUDE EARTHQUAKE 20/20'